services:
  mariadb:
    image: mariadb
    container_name: amatl-mariadb
    restart: unless-stopped  
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: amatl
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
    volumes:
      - mariadb-data:/var/lib/mysql

  amatlserver:
    build:
      context: .
      dockerfile: ./misc/docker/Dockerfile
    container_name: amatl-server
    restart: unless-stopped  
    image: reg.cadoles.com/envole/amatl
    depends_on: 
      - mariadb
    ports:
      - "8008:80"
    volumes:
      - .:/app:delegated

  adminer:
    image: adminer
    container_name: amatl-adminer
    restart: always
    ports:
      - 6088:8080
  corpus:
    image: ghcr.io/bornholm/corpus:latest
    container_name: corpus_container
    restart: unless-stopped
    network_mode: "host"
    environment:
      - CORPUS_LLM_PROVIDER_KEY=changeme
      - CORPUS_LLM_PROVIDER_BASE_URL=https://api.mistral.ai/v1/
      - CORPUS_LLM_PROVIDER_CHAT_COMPLETION_MODEL=mistral-small-latest
      - CORPUS_LLM_PROVIDER_EMBEDDINGS_MODEL=mistral-embed
    volumes:
      - corpus_data:/data
    stdin_open: true
    tty: true

volumes:
  mariadb-data:
  corpus_data:

