parameters:
  appEnv: "%env(resolve:APP_ENV)%"
  appSecret: "%env(resolve:APP_SECRET)%"
  appName: "%env(resolve:APP_NAME)%"
  appNoreply: "%env(resolve:APP_NOREPLY)%"
  modeAuth: "%env(resolve:MODE_AUTH)%"
  casHost: "%env(resolve:CAS_HOST)%"
  casPort: "%env(resolve:CAS_PORT)%"
  casPath: "%env(resolve:CAS_PATH)%"
  casUsername: "%env(resolve:CAS_USERNAME)%"
  casMail: "%env(resolve:CAS_MAIL)%"
  casLastname: "%env(resolve:CAS_LASTNAME)%"
  casFirstname: "%env(resolve:CAS_FIRSTNAME)%"


services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Security\DynamicAuthenticator:
    arguments:
      $modeAuth: '%env(MODE_AUTH)%'
